export const PROPERTY_CONFIGURATION_LIMITS = Object.freeze({
  propertyIdMaxLength: 64,
  nameMaxLength: 120,
  summaryMaxLength: 500,
  countryCodeLength: 2,
  timezoneMaxLength: 64,
  currencyCodeLength: 3,
  propertyTypeMaxLength: 32,
  bedTypeMaxLength: 16,
  amenityMaxLength: 80,
  hostNotesMaxLength: 2_000,
  operationalNotesMaxLength: 4_000,
  maxBedroomCount: 100,
  maxBathroomCount: 100,
  maxGuests: 200,
  maxBedConfigurations: 16,
  maxBedQuantity: 100,
  maxAmenities: 32,
});
